language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
before_install:
  - source $TRAVIS_BUILD_DIR/install.sh
script:
  - build_platform uno
  
install:
  - arduino --install-library "Servo","SPI","EEPROM","SoftwareSerial","Wire","WiFi",
notifications:
  email:
    on_success: change
on_failure: change
